blank_issues_enabled: false
contact_links:
  - name: LibMan CLI issues
    url: https://github.com/aspnet/LibraryManager/issues
    about: For problems with the underlying LibMan CLI itself (not this plugin).
